server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rms
    username: postgres
    password: rms@db


rms:
  jwt:
    secret: backendServicesApiSystemSecRetKeyValue
    validation-time: 600000
    refresh-time: 86400000

  openapi:
    local-url: http://localhost:8088
    dev-url: http://localhost:8088